
stages:
  - arch-x86_64
  - deb-x86_64


arch-x86_64:
  image: archlinux:base-devel

  before_script:
    - pacman -Syu --needed --noconfirm
    - useradd -m build
    - echo "build ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

  script:
    - cd ./PKGBUILD/arch/
    - sudo -u build makepkg --clean --rmdeps --syncdeps --noconfirm --noprogressbar
  
  artifacts:
    paths:
      - ./PKGBUILD/arch/*.pkg.tar.zst
    expire_in: 1 week
  
  stage: arch-x86_64


deb-x86_64:
  image: proget.hunterwittenborn.com/docker/makedeb/ci-image:stable
  
  before_script:
    - sudo apt-get update -y
    - sudo apt-get upgrade -y

  script:
    - cd ./PKGBUILD/deb/
    - makedeb --rm-deps --sync-deps --no-confirm

  artifacts:
    paths:
      - ./PKGBUILD/deb/*.deb
    expire_in: 1 week

  stage: deb-x86_64
