image: archlinux:latest

before_script:
  - pacman -Sy --needed --noconfirm sudo
  - useradd -m dev
  - echo "dev ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
  - su dev

stages:
  - build

makepkg:
  script:
    - makepkg --clean --rmdeps --syncdeps --noarchive --noconfirm --noprogressbar --asdeps
  stage: build
