image: archlinux:latest

before_script:
  - pacman -Su pkgbuild-introspection --noconfirm

stages:
  - build

makepkg:
  script:
    - makepkg --clean --rmdeps --syncdeps --noarchive --noconfirm --noprogressbar --asdeps
  stage: build
