stages:
  - archlinux:base-devel-x86_64
  - debian:latest-x86_64
  - ubuntu:latest-x86_64


# Build a package using the latest base-devel Docker image for Arch with `makepkg`
archlinux:base-devel-x86_64:
  image: nickgirga/aur-girga-build

  before_script:
    - pacman -Syu --needed --noconfirm

  script:
    - cd ./PKGBUILD/Arch/
    - sudo -u build makepkg --syncdeps --noconfirm --noprogressbar

  only:
    - milk
  
  artifacts:
    paths:
      - ./PKGBUILD/Arch/*.pkg.tar.zst
    expire_in: 1 week
  
  stage: archlinux:base-devel-x86_64


# Build a package using the latest Docker image for Debian with `makedeb`
debian:latest-x86_64:
  image: proget.makedeb.org/docker/makedeb/makedeb-beta:debian-latest
  
  before_script:
    - sudo apt-get update -y
    - sudo apt-get upgrade -y
    - sudo apt-get install -y git

  script:
    - cd ./PKGBUILD/Debian/
    - makedeb --sync-deps --no-confirm

  only:
    - milk

  artifacts:
    paths:
      - ./PKGBUILD/Debian/*.deb
    expire_in: 1 week

  stage: debian:latest-x86_64


# Build a package using the latest Docker image for Ubuntu with `makedeb`
ubuntu:latest-x86_64:
  image: proget.makedeb.org/docker/makedeb/makedeb-beta:ubuntu-latest
  
  before_script:
    - sudo apt-get update -y
    - sudo apt-get upgrade -y
    - sudo apt-get install -y git

  script:
    - cd ./PKGBUILD/Ubuntu/
    - makedeb --sync-deps --no-confirm

  only:
    - milk

  artifacts:
    paths:
      - ./PKGBUILD/Ubuntu/*.deb
    expire_in: 1 week

  stage: ubuntu:latest-x86_64
