image: nickgirga/arch-girga-build:latest

before_script:
  - sudo pacman -Sy --needed --noconfirm sudo

stages:
  - build

makepkg:
  script:
    - cd ./PKGBUILD/
    - makepkg --clean --rmdeps --syncdeps --noconfirm --noprogressbar
  artifacts:
    paths:
      - chocolate-box-git-*-any.pkg.tar.zst
    expire_in: 1 week
  stage: build
