image: archlinux:base-devel

before_script:
  - pacman -Syu --needed --noconfirm
  - useradd -m build
  - echo "build ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

stages:
  - build

arch-linux:
  script:
    - cd ./PKGBUILD/Arch/
    - sudo -u build makepkg --clean --rmdeps --syncdeps --noconfirm --noprogressbar
  artifacts:
    paths:
      - ./PKGBUILD/Arch/*.pkg.tar.zst
    expire_in: 1 week
  stage: build
